### ISSUE TITLE
Add PHP 7.0 and SF 3.0 support

### ISSUE THREAD

**Issue by jdecool** [novaway/NovawayFileManagementBundle#74]
According to Travis result, the bundle is not compatible with :
- PHP 7.0
- Symfony 3.0

I think, PHP 7.0 problem is linked to the older atoum version which is used.

**Comment by skwi** [comment]
I agree regarding the PHP 7.0 failure being link to atoum.
I don't know though if other compatibility issues will appear once this version matching is resolved.

The SF3.0 compatibility issue lies in the usage fo the deprecated `setDefaultOptions` method of the [OptionResolver Component](http://symfony.com/doc/current/components/options_resolver.html).
Still there is [a solution provide downgrade functionality](http://stackoverflow.com/questions/27225778/sf2-6-optionsresolverinterface-deprecated-and-abstracttypesetdefaultoptions/28671099#28671099)

**Comment by skwi** [comment]
Fixed in PR #73 

Travis tests fails for PHP7 because of a segmentation fault but works in a dockerized PHP 7 environment.

As PHP 7 support is currently an *allowed failure* for this project, I will take more time to look at it if the build keep failing in the future.

Therefore, PR #73 can be merged if +1'ed

**Comment by jdecool** [comment]
Travis issue is fixed in PR #75

After the merge, it's OK to update master with current 3.0 branch as long as the v4 is not ready.
